// src/layouts/main/header.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import Image from 'next/image'

export default function Header() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen)
  }

  return (
    <header className="fixed top-0 left-0 right-0 bg-[#171717] text-white z-50 h-16 border-b-2 border-black">
      <div className="px-4 h-full flex items-center justify-between">
        {/* Logo - left on desktop, centered on mobile */}
        <div className="flex-1 md:flex-none pr-0 md:pr-5">
          <Link
            href="/"
            className="flex items-center justify-center md:justify-start"
          >
            <div className="relative h-10 w-10 mr-0 md:mr-2">
              <Image
                src="/images/favicon.svg"
                alt={process.env.NEXT_PUBLIC_APP_NAME!}
                fill
                className="object-contain"
              />
            </div>
            <h2 className="text-2xl font-bold hidden md:inline">AgroComm</h2>
          </Link>
        </div>

        {/* Burger menu for mobile */}
        <button
          className="md:hidden text-white focus:outline-none"
          onClick={toggleMenu}
          aria-label={isMenuOpen ? 'Fechar menu' : 'Abrir menu'}
        >
          <svg
            className="w-6 h-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            {isMenuOpen ? (
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            ) : (
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M4 6h16M4 12h16M4 18h16"
              />
            )}
          </svg>
        </button>

        {/* Desktop navigation */}
        <nav className="hidden md:flex items-center space-x-6">
          <Link href="/" className="hover:text-green-200 transition-colors">
            Início
          </Link>
          <Link
            href="/produtos"
            className="hover:text-green-200 transition-colors"
          >
            Produtos
          </Link>
          <Link
            href="/mercado"
            className="hover:text-green-200 transition-colors"
          >
            Mercado
          </Link>
          <Link
            href="/cotacoes"
            className="hover:text-green-200 transition-colors"
          >
            Cotações
          </Link>
          <Link
            href="/contato"
            className="hover:text-green-200 transition-colors"
          >
            Contato
          </Link>
          <div className="flex items-center space-x-2 ml-4">
            <Link
              href="/login"
              className="px-4 py-2 border border-white rounded hover:bg-white hover:text-green-800 transition-colors"
            >
              Login
            </Link>
            <Link
              href="/cadastro"
              className="px-4 py-2 bg-white text-green-800 rounded hover:bg-green-200 transition-colors"
            >
              Cadastro
            </Link>
          </div>
        </nav>
      </div>

      {/* Mobile menu */}
      {isMenuOpen && (
        <div className="md:hidden bg-green-700 absolute w-full">
          <div className="container mx-auto px-4 py-2">
            <nav className="flex flex-col space-y-3 py-4">
              <Link
                href="/"
                className="hover:text-green-200 transition-colors py-2"
                onClick={() => setIsMenuOpen(false)}
              >
                Início
              </Link>
              <Link
                href="/produtos"
                className="hover:text-green-200 transition-colors py-2"
                onClick={() => setIsMenuOpen(false)}
              >
                Produtos
              </Link>
              <Link
                href="/mercado"
                className="hover:text-green-200 transition-colors py-2"
                onClick={() => setIsMenuOpen(false)}
              >
                Mercado
              </Link>
              <Link
                href="/cotacoes"
                className="hover:text-green-200 transition-colors py-2"
                onClick={() => setIsMenuOpen(false)}
              >
                Cotações
              </Link>
              <Link
                href="/contato"
                className="hover:text-green-200 transition-colors py-2"
                onClick={() => setIsMenuOpen(false)}
              >
                Contato
              </Link>
              <div className="flex flex-col space-y-2 pt-2 border-t border-green-600">
                <Link
                  href="/login"
                  className="px-4 py-2 border border-white rounded text-center hover:bg-white hover:text-green-800 transition-colors"
                  onClick={() => setIsMenuOpen(false)}
                >
                  Login
                </Link>
                <Link
                  href="/cadastro"
                  className="px-4 py-2 bg-white text-green-800 rounded text-center hover:bg-green-200 transition-colors"
                  onClick={() => setIsMenuOpen(false)}
                >
                  Cadastro
                </Link>
              </div>
            </nav>
          </div>
        </div>
      )}
    </header>
  )
}

// apps/site/src/components/header.vue
<script setup lang="ts">
import { ref } from 'vue'
import UserBar from '@/components/userbar.vue'

const appName = import.meta.env.VITE_APP_NAME!
const open = ref(false)
</script>
<template>
  <header class="fixed w-full top-0 z-10 bg-sonokai-bg_dim border-0 border-b-2 border-sonokai-border">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="relative flex h-16 items-center justify-between">
        <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
          <button @click="open = !open" type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white outline-none" aria-controls="mobile-menu" aria-expanded="false">
            <span class="absolute -inset-0.5"></span>
            <span class="sr-only">Open main menu</span>
            <svg class="h-6 w-6" :class="{ 'block': !open, 'hidden': open }" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
            <svg class="h-6 w-6" :class="{ 'block': open, 'hidden': !open }" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
          <router-link to="/" class="flex flex-shrink-0 items-center logo">
            <img class="h-10 w-auto md:me-2" src="/images/navbar.svg" :alt="appName">
            <span class="hidden md:block font-extrabold text-2xl text-sonokai-fg hover:text-sonokai-fg bg-transparent">{{ appName }}</span>
          </router-link>
          <div class="hidden sm:ml-6 sm:block">
            <div class="flex space-x-4">
              <router-link to="/" class="rounded-md bg-sonokai-black px-3 py-2 font-bold text-sonokai-fg hover:text-sonokai-fg">
                <font-awesome-icon icon="fa-solid fa-house" />
                Início
              </router-link>
              <!-- <router-link to="/" class="rounded-md px-3 py-2 font-bold text-gray-300 hover:bg-gray-700 hover:text-white">Team</router-link> -->
            </div>
          </div>
        </div>
        <user-bar />
      </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="sm:hidden" :class="{ 'block': open, 'hidden': !open }" id="mobile-menu">
      <div class="space-y-1 px-2 pb-3 pt-2">
        <router-link to="/" class="block rounded-md bg-sonokai-black px-3 py-2 text-base font-medium text-white">Início</router-link>
        <!-- <router-link to="/" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</router-link> -->
      </div>
    </div>
  </header>
</template>
<style scoped lang="scss">
.active {
  @apply transition ease-in-out bg-sonokai-black duration-300 hover:text-sonokai-fg;
}

.logo.active {
  @apply transition ease-in-out bg-transparent duration-300 hover:text-sonokai-fg;
}
</style>
